apiVersion: v1
kind: Service
type: NodePort
metadata:
  name: nginx
spec:
  type: NodePort 
  selector:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
    demo: np
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-np
  lables:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
    demo: np
spec:
  containers:
    - name: nginx
      image: nginx
