kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    lables:
      project: expense
      environment: dev
      component: backend
      version: "1.0.0"
      demo: lp
    ports:
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
---

kind: Pod
apiVersion: v1
metadata:
  name: backend-lb
  lables:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
    demo: lp
spec:
  containers:
  - name: nginx
    image: nginx
